spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  kakao:
    userApiUrl: ${USERAPIURL}

  data:
    redis:
      host: ${HOST}
      port: ${PORT}

  jwt:
    secretKey: ${SECRETKEY}
    refreshKey: ${REFRESHKEY}
    accessExp: ${ACCESSEXP}
    refreshExp: ${REFRESHEXP}

  mail:
    host: ${EMAILHOST}
    port: ${EMAILPORT}
    username: ${EMAILUSERNAME}
    password: ${EMAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  codeExp: ${CODEEXP}


  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${BUCKET}
      region:
        static: ${STATIC}
      stack:
        auto: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB