spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  kakao:
    userApiUrl: ${USERAPIURL}

  data:
    redis:
      host: ${HOST}
      port: ${PORT}

  jwt:
    secretKey: ${SECRETKEY}
    refreshKey: ${REFRESHKEY}
    accessExp: ${ACCESSEXP}
    refreshExp: ${REFRESHEXP}

  mail:
    host: smtp.gmail.com
    port: 587
    username: vvwv309@gmail.com
    password: ${EMAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  auth-code-expiration-millis: 1800000